name: validate

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, linux-latest ]

    steps:
      - name: checkout self
        uses: actions/checkout@v4

      - name: RageAgainstThePixel/setup-steamcmd
        uses: ./

      - run: 'steamcmd help'
