name: validate

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: checkout self
        uses: actions/checkout@v4

      - name: RageAgainstThePixel/setup-steamcmd
        uses: ./

      - run: |
          which steamcmd
          steamcmd +login anonymous +help +quit
          echo "$STEAM_DIR"
          logsDir="$STEAM_DIR/logs"
          echo "Logs dir: $logsDir"
          logFiles=$(ls "$logsDir")
          for logFile in $logFiles; do
            echo "::group::$logsDir/$logFile"
            cat "$logsDir/$logFile"
            echo "::endgroup::"
          done
        shell: bash
